#!/usr/bin/env python3
import json, os, subprocess, sys
from datetime import datetime, timezone
from pathlib import Path


def iso_now():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')


def load_targets(workspace):
    target_dir = Path(workspace) / 'targets'
    targets = []
    if target_dir.exists():
        for path in sorted(target_dir.glob('*.json')):
            with open(path, 'r', encoding='utf-8') as fh:
                targets.append(json.load(fh))
    return targets


def call_htmlcut(htmlcut_bin, target_id):
    proc = subprocess.run([htmlcut_bin, '--target', target_id], capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or 'htmlcut fixture failed')
    payload = json.loads(proc.stdout)
    return payload.get('text', '')


def make_run(target, htmlcut_bin):
    target_id = target['id']
    extracted = call_htmlcut(htmlcut_bin, target_id)
    status = 'changed' if target_id.endswith('availability') else 'unchanged'
    run_id = f"run-{target_id}-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}"
    return {
        'runId': run_id,
        'targetId': target_id,
        'status': status,
        'summary': f"Fixture FFHN processed {target['name']}.",
        'startedAt': iso_now(),
        'finishedAt': iso_now(),
        'command': f"ffhn run --target {target_id} --json",
        'stdout': json.dumps({'status': status, 'targetId': target_id, 'extractedText': extracted}, indent=2),
        'stderr': '',
        'note': 'Generated by the FFHN live fixture.',
        'extractedText': extracted,
        'mode': 'sidecar-live'
    }


def main():
    args = sys.argv[1:]
    if not args:
        print(json.dumps({'ok': False, 'error': 'missing command'}))
        sys.exit(2)

    htmlcut_bin = os.environ.get('FFHN_HTMLCUT_BIN') or os.environ.get('FFHN_DESKTOP_HTMLCUT_BIN')
    if not htmlcut_bin:
        print(json.dumps({'ok': False, 'error': 'FFHN_HTMLCUT_BIN not set'}))
        sys.exit(3)

    command = args[0]
    if command == 'probe':
        print(json.dumps({'ok': True, 'mode': 'sidecar-live', 'note': 'FFHN fixture launched successfully.'}))
        return

    workspace = '.'
    if '--workspace' in args:
        i = args.index('--workspace')
        if i + 1 < len(args):
            workspace = args[i+1]

    if command == 'run':
        if '--target' not in args:
            print(json.dumps({'ok': False, 'error': 'missing --target'}))
            sys.exit(2)
        i = args.index('--target')
        target_id = args[i+1]
        targets = {t['id']: t for t in load_targets(workspace)}
        if target_id not in targets:
            print(json.dumps({'ok': False, 'error': f'unknown target: {target_id}'}))
            sys.exit(4)
        run = make_run(targets[target_id], htmlcut_bin)
        print(json.dumps({'ok': True, 'mode': 'sidecar-live', 'runs': [run]}))
        return

    if command == 'run-all':
        runs = [make_run(t, htmlcut_bin) for t in load_targets(workspace)]
        print(json.dumps({'ok': True, 'mode': 'sidecar-live', 'runs': runs}))
        return

    print(json.dumps({'ok': False, 'error': f'unknown command: {command}'}))
    sys.exit(2)


if __name__ == '__main__':
    main()
